### ISSUE TITLE
Audit: unsafe policy actions should be tracked in Audit

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#1004]
Relates to #115 

Warrants discussion but here is a quote

- we’d probably want to add a new action type with a prefix of `unsafe_` or something similar
  - the other option I can see would be updating the object type since we’re already adding a bunch of those, but it doesn’t feel right since the “object” isn’t really unsafe itself, but the action being performed is
  - would probably need to sync with @dreyes29 about adding new action types, although I think we’re already assuming we’re doing that through the rewrap action type we’re creating?
- reactivation would be `unsafe_update` to follow suit with deactivation being update
- for cascading deletes I’d imagine everything in the cascade that gets deleted would also inherit the `unsafe_` action type? Either that or the ones that already support “safe deletion” would just have regular deletes

**Comment by ryanulit** [comment]
After further discussion with @jakedoublev, we've decided to add an additional property to the audit event to indicate the endpoint called in a request.  This not only adds more context to the audit data, but also allows consumers to know that an unsafe method was called without us needing to arbitrarily add an additional `isUnsafe` or similar property to the audit event.

**Comment by ryanulit** [comment]
After even further discussion with @jrschumacher, the decision is to not add anything else to the audit event object after all.  All that will be done for this work is adding the audit log calls to the unsafe service operations, leaving the door open for future improvements once we have a better story and sample data around audit.  We will **not** introduce a new property to track the endpoint.
