### ISSUE TITLE
Unexpected emails in access decisions returns a 500 error

### ISSUE THREAD

**Issue by BenGirone** [opentdf/platform#1036]
To reproduce, put an email in an access decision like `bob@unexpected.com`

I can provide some logs and specifics if it isn't immediately reproducible.

**Comment by jrschumacher** [comment]
@BenGirone will you provide sample input and the output you get? Also, what is the behavior you are expecting?

**Comment by BenGirone** [comment]
> @BenGirone will you provide sample input and the output you get? Also, what is the behavior you are expecting?

Cody was able to reproduce it again. simply put an email that the system won't expect in an entity and you should get an output like this

`ime=2024-07-08T11:19:35.395-05:00 level=ERROR msg="error from entity resolution: {\"body\": {\"code\": 2, \"details\": [], \"message\": \"code:5 message:\\\"resource retrieval failed\\\" entity:\\\"unexpected@example.com\\\"\"}, \"headers\": {\"content-length\": [\"110\"], \"content-type\": [\"application/json\"], \"date\": [\"Mon, 08 Jul 2024 16:19:35 GMT\"], \"vary\": [\"Origin\"]}, \"raw_body\": \"{\\\"code\\\":2,\\\"message\\\":\\\"code:5 message:\\\\\\\"resource retrieval failed\\\\\\\" entity:\\\\\\\"unexpected@example.com\\\\\\\"\\\",\\\"details\\\":[]}\", \"status\": \"500 Internal Server Error\", \"status_code\": 500}" namespace=sharepoint error="error from entity resolution: {\"body\": {\"code\": 2, \"details\": [], \"message\": \"code:5 message:\\\"resource retrieval failed\\\" entity:\\\"unexpected@example.com\\\"\"}, \"headers\": {\"content-length\": [\"110\"], \"content-type\": [\"application/json\"], \"date\": [\"Mon, 08 Jul 2024 16:19:35 GMT\"], \"vary\": [\"Origin\"]}, \"raw_body\": \"{\\\"code\\\":2,\\\"message\\\":\\\"code:5 message:\\\\\\\"resource retrieval failed\\\\\\\" entity:\\\\\\\"unexpected@example.com\\\\\\\"\\\",\\\"details\\\":[]}\", \"status\": \"500 Internal Server Error\", \"status_code\": 500}" extra="getEntitlements request failed"
time=2024-07-08T11:19:35.395-05:00 level=ERROR msg="Error fetching access decisions from Access Service" namespace=sharepoint error="rpc error: code = Internal desc = resource retrieval failed"`

**Comment by cody-lettau** [comment]
The expectation would be that we receive a DENY decision for a user who is unknown to the platform.

**Comment by jrschumacher** [comment]
Thank you. There is a draft PR which will resolve this. I'm going to update the issue to use the actual error of 500 rather than panic.

**Comment by cassandrabailey293** [comment]
Fixed by #1113
