### ISSUE TITLE
Remove HSM support from OpenTDF

### ISSUE THREAD

**Issue by cassandrabailey293** [opentdf/platform#1049]
HSM will not be directly supported in OpenTDF. Downstream projects that want to enable HSM support will need an extension point to configure an external crypto provider.

Acceptance Criteria
* remove HSM support from OpenTDF
* create and document extension point for developers who want to use HSM or other external crypto providers

**Comment by dmihalcik-virtru** [comment]
I'd like to move the 'create and document extension point' to https://github.com/opentdf/platform/issues/1254
