### ISSUE TITLE
Authorization GetEntitlements should consider hierarchical attribute values in entitlement values response

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#1054]
### Background

As the behavior of the platform is that any TDF can be encrypted with any attribute FQN without precondition or validation that the attributes exist on TDF creation, it is a PEP concern to drive UX around TDF creation.

If I am entitled to an `anyOf` attribute value, an `allOf` attribute value, and a specific `hierarchy` attribute value that is third of five values, the current Authorization Service behavior is to return the precise values I am entitled to, which would be `anyOf:exampleValue`, `allOf:exampleValue`, `hierarchy:third` even though I can access `hierarchy:fourth` and `hierarchy:fifth` due to the attribute definition rule.

Due to this, a PEP built on top of the platform must do their own work to fetch a user's entitlements, seek out any hierarchical attributes, and check a user's entitlement level against the potential values to drive a UX where they are able to TDF data at lower values than their entitlement level. This is intuitive: a GetDecisions request would allow the user to access `hierarchy:fourth` and `hierarchy:fifth` given a user's entitlement to `hierarchy:third`, so the PEP should drive UX where those are "accessible" values.

### Acceptance Criteria

1. `GetEntitlements` should support a new query parameter to return all attributes an entity would be entitled to
2. If that new parameter is provided, the response should consider both the attribute rule _and_ the resolved subject mappings instead of _only_ the subject mappings (i.e. `with_comprehensive` or some other selector parameter) so the hierarchy scenario is handled elegantly
3. The current API behavior without that parameter should remain the same
4. Tests

**Comment by pflynn-virtru** [comment]
@elizabethhealy should this be handled in `authorization.go` or OPA?

@jakedoublev do we need a new option `with_comprehensive` or can we change this behavior for all?

**Comment by jakedoublev** [comment]
> @jakedoublev do we need a new option with_comprehensive or can we change this behavior for all?

@dmihalcik-virtru had the below feedback to this original request:

```
Some context:
    - Returning only the highest value helps keep the size of the response small - notably, we previously would embed the entity attributes in the Authorization header, so we had a strict size limit on entity attribute size
    - The matcher in python KAS would require all data attributes to match. So if a policy was labelled `highest`, any `lowest` entity attributes found in the JWT would cause the policy to fail.
    - I still think we probably just want to return the maximum value, although we could update query parameters to indicate:
        - list all values the entity has access to
        - get the highest value the user has access to below level X, to allow granting least privilege.  For example, a client may not wish. to expose to a PDP that the entity has `highest` attribute value to access a `medium` or `lowest` document
```

**Comment by elizabethhealy** [comment]
> @elizabethhealy should this be handled in `authorization.go` or OPA?
> 
> 
> 
> @jakedoublev do we need a new option `with_comprehensive` or can we change this behavior for all?

i think authorization, the opa side is just doing ers and subject mapping evaluation, it doesn't really care about attributes

i'm guessing it should be like after we get the final list of attributes for an entity, we look back at the get attributevalesbyfqn response and check the rule for hierarchy. it'll prolly need to reuse some of the code from get decision that handles the order/rank
