### ISSUE TITLE
Add contains subject operator type

### ISSUE THREAD

**Issue by ttschampel** [opentdf/platform#1080]
Add support for a **contains** subject mapping operator type to support string contains functionality on the subject mapping external selected value.  

Reference - currently SubjectMappingOperatorEnum types

```
enum SubjectMappingOperatorEnum {
  SUBJECT_MAPPING_OPERATOR_ENUM_UNSPECIFIED = 0;
  SUBJECT_MAPPING_OPERATOR_ENUM_IN = 1;
  SUBJECT_MAPPING_OPERATOR_ENUM_NOT_IN = 2;
}

```

### Contains Example : 
The below would be a positive match for the condition & user

**The Condition:**
```
 {
     "subject_external_selector_value": "'.email'",
     "operator": "SUBJECT_MAPPING_OPERATOR_ENUM_CONTAINS",
     "subject_external_values" : ["@opentdf.io"]
   }
```
 **user**:
```
 {"email":"sample@opentdf.io"}
```

**Comment by jrschumacher** [comment]
@ttschampel could we add

- contains
- begins with
- ends with

**Comment by ttschampel** [comment]
I'm good with contains, starts with, ends with;  might as well add these all at once

**Comment by cassandrabailey293** [comment]
we can split out "starts with" and "ends with" into separate issues so we can make sure we address this this week.
