### ISSUE TITLE
Move ERS call out of rego

### ISSUE THREAD

**Issue by elizabethhealy** [opentdf/platform#1217]
Currently, we call ERS from inside rego. 
Rego only supports http calls and we'd like the ability to hit ERS with grpc. Additionally this would remove some complexity from the rego input.

With this change, the new inputs to the rego would be a list of entity representations (returned from ERS) and the relevant subject mappings.

<img width="784" alt="Screenshot 2024-07-26 at 12 13 57 PM" src="https://github.com/user-attachments/assets/9768e767-f1d7-40a0-8117-09e4baa76be6">
<img width="763" alt="Screenshot 2024-07-26 at 12 21 37 PM" src="https://github.com/user-attachments/assets/f812ade1-6d68-42e4-925e-9b74bc055aed">

**Comment by strantalis** [comment]
@elizabethhealy I wonder if we could not pass in subject mappings but instead inside of the builtin func call `MatchSubjctMappings` rpc.

**Comment by elizabethhealy** [comment]
> MatchSubjctMappings

@strantalis has `MatchSubjctMappings` been implemented? i remember it was planned but hadn't heard anything about it

**Comment by strantalis** [comment]
@elizabethhealy I think @jakedoublev implemented this a while back.

https://github.com/opentdf/platform/blob/5aef245720cb417a51622ffd1276f57163319c6d/service/policy/subjectmapping/subject_mapping.go#L163-L176

**Comment by damorris25** [comment]
This is a good idea.
