### ISSUE TITLE
platform defined default kas

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#1221]
Today a policy enforcement point is required to pass in at least 1 key access server even with the introduction of attribute based key splitting. A pep should not have to do this and a platform administrator should be able to define a global default KAS if the data attributes on the tdf don't contain a key access server information. 

**Option 1**: There are probably a few options around this but one of them could be to define a generic extension point in the config the wellknown service loads and is able to send back to our sdks. 

**Option 2**: Always run a KAS within the core platform. This way the platform endpoint will always be the default kas if no kas info is defined for a set of attributes. 

**Option 3**:  Set default KAS on the attribute namespace.

**Comment by pflynn-virtru** [comment]
Option 2 Each platform has a KAS

We seem to be trending to each PEP has a KAS

**Comment by jrschumacher** [comment]
I'm not sure I see us moving towards each PEP having a KAS, but I agree by default we should add a KAS to each namespace. This is especially true when running as a monolith.

**Comment by cassandrabailey293** [comment]
Notes from discussion
* ~~option 1~~ , feels less elegant than other solutions
* ~~option 2~~, issue with this is that users will want to run KAS separately from monolith in production, point to a KAS outside of their platform deployment, etc.  
* option 3, this option may be the best default option. 
* might need to refine approach based on split key work that has been ongoing.
*  will it prevent or hinder brokering or networking with KASes in the future?  

Next steps  
* select option 3 tentatively, discuss how it will integrate with split key work

**Comment by jakedoublev** [comment]
Related to https://github.com/opentdf/platform/issues/1296#issuecomment-2291819700
