### ISSUE TITLE
SDK should support `WithOIDCAccessToken` option

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#1307]
### Background

Currently, the [otdfctl CLI](https://github.com/opentdf/otdfctl/pull/144) is only able to authenticate users through the client credentials flow, which is itself a limitation of the SDK (relying on the [WithClientCredentials option](https://github.com/opentdf/platform/blob/cfab3ad8a72f3a2f1a28ccca988459ddcdcbd7f6/sdk/options.go#L74)). There is also another supported option [WithTokenExchange](https://github.com/opentdf/platform/blob/cfab3ad8a72f3a2f1a28ccca988459ddcdcbd7f6/sdk/options.go#L120-L129). However, the CLI and other clients should not be required to necessarily utilize on a token exchange flow when they may be driven by an entity directly (as in the case of a CLI) and there are cases where the client should be of lower trust.

### Acceptance Criteria

1. SDK authenticates gRPC requests with a passed in OIDC Access Token
2. Unit tests

**Comment by strantalis** [comment]
@jakedoublev What if we just exposed this option. This way you can just define your own TokenSource implementation. 

https://github.com/opentdf/platform/blob/cfab3ad8a72f3a2f1a28ccca988459ddcdcbd7f6/sdk/auth/access_token_source.go#L12-L17

https://github.com/opentdf/platform/blob/main/sdk/options.go#L96-L100

**Comment by jakedoublev** [comment]
That seems like it would work. There are a couple of abstractions/interfaces that make it a little tricky to know for sure but it would be good to try it out and see. I'm not sure we'll need [an http client in the AccessToken method signature](https://github.com/opentdf/platform/blob/main/sdk/auth/token_adding_interceptor.go#L53) for example since we'll have already gone through a flow to get/store an OIDC AT within at least the CLI, but we could just ignore that argument I guess if we indeed don't need it.

**Comment by strantalis** [comment]
> @strantalis That seems like it would work. There are a couple of abstractions/interfaces that make it a little tricky to know for sure but it would be good to try it out and see. I'm not sure we'll need [an http client in the AccessToken method signature](https://github.com/opentdf/platform/blob/main/sdk/auth/token_adding_interceptor.go#L53) for example since we'll have already gone through a flow to get/store an OIDC AT within at least the CLI, but we could just ignore that argument I guess if we indeed don't need it.

I am actually not sure why we are passing that in as well. Let me know if I can help with this.
