### ISSUE TITLE
Authorization tab not coming while creating client

### ISSUE THREAD

**Issue by Vivekmauli14** [opentdf/platform#1463]
Hi,
I followed this guide in setting up keycloak client https://www.keycloak.org/docs/latest/authorization_services/#_resource_server_create_client
however I was unable to get this Authorization tab in my setup, any clue on what is going wrong with my setup?
thanks!

[https://ibb.co/8bVzt5f](url)

**Comment by jrschumacher** [comment]
Hi @Vivekmauli14 unfortunately we don't provide support for Keycloak. My advice is to use the [Keycloak Discussions](https://github.com/keycloak/keycloak/discussions) to understand why you're not seeing the expected tabs in Keycloak.
