### ISSUE TITLE
Panic possible in `granter` with possible invalid name and value inputs

### ISSUE THREAD

**Issue by jentfoo** [opentdf/platform#1468]
It was discovered through fuzzing that there are several cases where a `NewAttributeValueFQN` can pass without error but subsequent actions on it could result in a panic.

**Comment by jrschumacher** [comment]
@jentfoo would you be able to post an example where this is the case

**Comment by jentfoo** [comment]
@jrschumacher I will provide examples in an upcoming PR, just doing some final testing now
