### ISSUE TITLE
Policy: Implement gRPC interceptors for debug logging of service requests

### ISSUE THREAD

**Issue by ryanulit** [opentdf/platform#1480]
Add gRPC unary interceptors for all Policy services that log the requests and responses received by the service methods

**Comment by pflynn-virtru** [comment]
Will this suffice?

```
export GRPC_GO_LOG_VERBOSITY_LEVEL=99
export GRPC_GO_LOG_SEVERITY_LEVEL=info
```

https://github.com/grpc/grpc-go/blob/master/README.md#how-to-turn-on-logging

**Comment by cassandrabailey293** [comment]
we will revisit need for logging in the future - this is not a critical issue, closing until further investigation of logging strategy is done.
