### ISSUE TITLE
Authorization service is logging the subject mappings during an AccessPDP check

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#1503]
There is somewhere in the code that is logging all subject mappings when log level is set to debug. Debug log level should still be performant even when debugging an issue. With the log being so large, this could potentially decrease performance as subject mappings are added.

Find in the code where this log statement is taking place and remove it or change it to trace level log.

## Acceptance Criteria:

- Remove the excessive logging of subject mappings

**Comment by elizabethhealy** [comment]
some places where the logs are big
https://github.com/opentdf/platform/blob/144aeda9141123cbfad44271844df49d632744f2/service/internal/access/pdp.go#L56
https://github.com/opentdf/platform/blob/144aeda9141123cbfad44271844df49d632744f2/service/internal/access/pdp.go#L267

**Comment by strantalis** [comment]
Also https://github.com/opentdf/platform/blob/144aeda9141123cbfad44271844df49d632744f2/service/internal/access/pdp.go#L568-L571
