### ISSUE TITLE
Spike: investigate adding connectrpc support

### ISSUE THREAD

**Issue by suchak1** [opentdf/platform#1519]
We need a comprehensive solution to support not only gRPC and HTTP2 but also seamlessly fallback on HTTP when HTTP2 is not available.

**Comment by jrschumacher** [comment]
@suchak1 @dmihalcik-virtru @suchak1, added some links I found to the description

**Comment by suchak1** [comment]
### Results
_platform_: All RPCs, clients, and registration functions were converted: https://github.com/opentdf/platform/pull/1521
Only one auth interceptor was converted (auth disabled).

_otdfctl_: All handlers were converted and platformEndpoint issue corrected: https://github.com/opentdf/otdfctl/compare/main...feature/connect

### Challenges
A full conversion to connect has required hundreds of changes. It would require many more in DSP (including tructl, and PEPs), resulting in large breaking changes. 

### Ideas
We could wrap the RPCs, create v2 versions of services, handlers, clients, etc, and package both grpc-gateway and connect implementations (perhaps on different ports). This wouldn't require new major versions, and we could convert downstream dependencies gradually.
