### ISSUE TITLE
Consider Adding a "name", or "commonName" column to the "KeyAccessServer" Table for more uniform UX

### ISSUE THREAD

**Issue by averypfeiffer** [opentdf/platform#153]
Currently, our KeyAccessServer schema consists of the following columns:

- uuid | "id"
- varchar | "uri"
- jsonb | "public_key"
- jsonb | "metadata"

And the proposed method for adding a "common name" for the KAS server being registered is to add a metadata object in the form of:
```
{
 "labels": {"name": "SOME_NAME" }
}
```

However, my concern is that this will lead to messy, and unreliable code, when attempting to display the KAS Name in say, a dropdown list or table in the browser (or other UI), as the name label, is not guarenteed to be present on the DB record. 

The solution would be to add a varchar "name" column to the "KeyAccessServer" table, so that we, as well as any future developers working on the DSP, can always rely on that field being present, and the customer has a simple way to differentiate between their registered KeyServers (without having to memorize the UUIDs)

**Comment by jakedoublev** [comment]
Pulled into `todo` to unblock https://github.com/opentdf/otdfctl/issues/257
