### ISSUE TITLE
SPIKE: Investigate current state of audit functionality for possible improvements

### ISSUE THREAD

**Issue by ryanulit** [opentdf/platform#1539]
Investigate current state to identify areas for improvement and include findings in a comment

**Comment by ryanulit** [comment]
## Current State

- Audit events are only logged for Create/Update/Delete requests; Get/List requests are NOT audited
- Audit events are logged by the service's service layer logic, using a custom `AUDIT` log level for easy indentification
- An audit object that contains the details of the event is created and marshalled to JSON, and then logged as the message body of the log entry
- An additional `namespace` slog param will typically be added to the log entry to identify the service context of the log


### Audit Process Flow

1. A request is made to a gRPC method:

```
// gRPC method
policy.attributes.AttributesService.UpdateAttributeValue

// request message
{
    "id": "c2140825-0969-44c9-8dd6-5d7e0a856b9c",
    "metadata": {
        "labels": [
            {
                "value": "newKey",
                "key": "newMe"
            }
        ]
    },
    "metadata_update_behavior": "METADATA_UPDATE_ENUM_EXTEND"
}
```

2. The service layer receives the request, makes the desired updates, and then creates an audit object to detail the changes made and additional metadata of the request:

```json
// NOTE: For testing purposes, this request was made without the production-required auth'n.  
// If the request is auth'd, the owner/actor objects and attributes would be populated with actual data, 
// but in this instance they are null or empty UUIDs.

{
  "object": {
    "type": "attribute_value",
    "id": "c2140825-0969-44c9-8dd6-5d7e0a856b9c",
    "attributes": {
      "assertions": null,
      "attrs": null
    }
  },
  "action": {
    "type": "update",
    "result": "success"
  },
  "owner": {
    "id": "00000000-0000-0000-0000-000000000000",
    "orgId": "00000000-0000-0000-0000-000000000000"
  },
  "actor": {
    "id": "None",
    "attributes": []
  },
  "eventMetaData": null,
  "clientInfo": {
    "userAgent": "grpc-node-js/1.6.9",
    "platform": "policy",
    "requestIp": "::1"
  },
  "diff": [
    {
      "op": "test",
      "path": "/metadata/created_at",
      "value": {
        "nanos": 3425000,
        "seconds": 1724790122
      }
    },
    {
      "op": "remove",
      "path": "/metadata/created_at"
    },
    {
      "op": "add",
      "path": "/metadata/labels",
      "value": {
        "newMe": "newKey"
      }
    },
    {
      "op": "test",
      "path": "/metadata/updated_at",
      "value": {
        "nanos": 722205000,
        "seconds": 1726253803
      }
    },
    {
      "op": "remove",
      "path": "/metadata/updated_at"
    }
  ],
  "requestId": "00000000-0000-0000-0000-000000000000",
  "timestamp": "2024-09-13T12:57:10-06:00"
}
```

3. The service layer then marshalls this audit object to JSON and creates the audit log entry:

```json
{
  "time": "2024-09-13T12:57:10.577236-06:00",
  "level": "AUDIT",
  "msg": "{\"object\":{\"type\":\"attribute_value\",\"id\":\"c2140825-0969-44c9-8dd6-5d7e0a856b9c\",\"attributes\":{\"assertions\":null,\"attrs\":null}},\"action\":{\"type\":\"update\",\"result\":\"success\"},\"owner\":{\"id\":\"00000000-0000-0000-0000-000000000000\",\"orgId\":\"00000000-0000-0000-0000-000000000000\"},\"actor\":{\"id\":\"None\",\"attributes\":[]},\"eventMetaData\":null,\"clientInfo\":{\"userAgent\":\"grpc-node-js/1.6.9\",\"platform\":\"policy\",\"requestIp\":\"::1\"},\"diff\":[{\"op\":\"test\",\"path\":\"/metadata/created_at\",\"value\":{\"nanos\":3425000,\"seconds\":1724790122}},{\"op\":\"remove\",\"path\":\"/metadata/created_at\"},{\"op\":\"add\",\"path\":\"/metadata/labels\",\"value\":{\"newMe\":\"newKey\"}},{\"op\":\"test\",\"path\":\"/metadata/updated_at\",\"value\":{\"nanos\":722205000,\"seconds\":1726253803}},{\"op\":\"remove\",\"path\":\"/metadata/updated_at\"}],\"requestId\":\"00000000-0000-0000-0000-000000000000\",\"timestamp\":\"2024-09-13T12:57:10-06:00\"}",
  "namespace": "policy"
}
```

## Problems with Current State
- Individual service layer Update methods [manually build the updated object being compared to the original object](https://github.com/opentdf/platform/blob/main/service/policy/namespaces/namespaces.go#L177-L186), which is tedious/boilerplate and prone to human error
- The object metadata fields `created_at` and `updated_at` are being included in the object diff, but are not actually necessary given the audit log entry has a `timestamp` field itself
- The diff library being used creates the diff structure as a JSON Patch object, which is likely harder to understand then just a simple git/file diff of the JSON structure

**Comment by jakedoublev** [comment]
Two questions:
1. Do you know where the `"op":"test"` diff `type` is or where precisely it's coming from? I see it [expected in unit test assertions](https://github.com/opentdf/platform/blob/d9a07f84ab5686fe13af82435af3201042dd7228/service/logger/audit/policy_test.go#L85) but am unclear if that just represents the before state of an audit diff. If it's the before state, maybe we should rename this.
2. Regarding zero values, it looks like we use `json.Marshal` throughout the [policy audit events](https://github.com/opentdf/platform/blob/d9a07f84ab5686fe13af82435af3201042dd7228/service/logger/audit/policy.go#L30), and maybe we should be using `protojson.Marshal` instead. Have you thought about this? I expect this change would help handle zero values more effectively, but we'd want to test.

**Comment by ryanulit** [comment]
> Two questions:
> 
> 1. Do you know where the `"op":"test"` diff `type` is or where precisely it's coming from? I see it [expected in unit test assertions](https://github.com/opentdf/platform/blob/d9a07f84ab5686fe13af82435af3201042dd7228/service/logger/audit/policy_test.go#L85) but am unclear if that just represents the before state of an audit diff. If it's the before state, maybe we should rename this.
> 2. Regarding zero values, it looks like we use `json.Marshal` throughout the [policy audit events](https://github.com/opentdf/platform/blob/d9a07f84ab5686fe13af82435af3201042dd7228/service/logger/audit/policy.go#L30), and maybe we should be using `protojson.Marshal` instead. Have you thought about this? I expect this change would help handle zero values more effectively, but we'd want to test.

1. From https://jsonpatch.com/#test:

> Tests that the specified value is set in the document. If the test fails, then the patch as a whole should not apply.

And it is getting added to our diff output because we have [specified](https://github.com/opentdf/platform/blob/main/service/logger/audit/utils.go#L140) the [jsondiff.Invertible()](https://pkg.go.dev/github.com/wI2L/jsondiff#Invertible) option when running the compare.

2. It wasn't related to zero values, but I ran into an issue with `json.Marshal` not marshalling `&wrapperspb.*` types correctly.  And yes, I had to switch to using `protojson` and cast the interfaces to `protoreflect.ProtoMessage` types.

**Comment by ryanulit** [comment]
Also, I think the real reason the `"op":"test"` operations are included is so that there is a before and after view of the change.  The alternative would be the git/file diff.

**Comment by ryanulit** [comment]
@jrschumacher @jakedoublev I've updated the write up to include what we've discussed.
