### ISSUE TITLE
Enable SoftHSM in default images

### ISSUE THREAD

**Issue by dmihalcik-virtru** [opentdf/platform#316]
We need to access HSMs for the key access service (KAS). For now, we will emulate the behavior with SoftHSM. Since we are using chain guard images, we will have to do the folliwing:

1. build a custom image with [apko](https://github.com/chainguard-dev/apko?tab=readme-ov-file#apko-apk-based-oci-image-builder) that includes [what is in the go image](https://github.com/chainguard-images/images/blob/main/images/go/config/template.apko.yaml)
2. Publish this image on a schedule I guess to GitHub container registry? 
  a.  alternatively we can build it locally when needed and use `docker load 
4. Update our Dockerfile to use the image
5. Update server.StartHSM to use the correct .so path depending on if alpine (`/usr/lib/softhsm/libsofthsm2.so`), ubuntu (`/lib/softhsm/libsofthsm2.so`) or homebrew   (`$(brew --prefix)/lib/softhsm/libsofthsm2.so`)
6. wire in access to use hsm

**Comment by strantalis** [comment]
Softhsm won't be included in the platform build and only used within ci for testing.
