### ISSUE TITLE
platform logging improvements

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#328]
- Formalize logging message format - lowercase, only period punctionation.
- Decide on and record Error codes
- Create logging integration test to enforce the above

- #710
- #712
- #715
- #716
- #720

**Comment by pflynn-virtru** [comment]
notes:
- Don't lose error, have an error stack trace, keep chain intact
- No fat. or log. statements.
- slog with errors.join
  - everytime you create an error, slog it, with some golang line or code block identifier 
  - ideally everything in one line log
  - slog.XXXWithContext
  - add service to Context so log messages show which service
- Include user error message, not just technical  -- error id, user message 
- Follow Java 

Users:
library users - error messaging through API and SDK
end users messaging

**Comment by pflynn-virtru** [comment]
possible option to log line number and package

**Comment by pflynn-virtru** [comment]
reference: https://betterstack.com/community/guides/logging/logging-in-go/

**Comment by biscoe916** [comment]
@strantalis @pflynn-virtru We're going to do this, we just need to flesh this ticket out a bit more.

**Comment by jrschumacher** [comment]
Could we also get something added to Github Discussions or the README about our logging practice to better onboard teams?
