### ISSUE TITLE
ADR: Policy API performance, open ended querying for entitlements (MatchedSubjectMappings) has known performance concerns at scale

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#365]
### Background

Once the work in https://github.com/opentdf/platform/pull/347 and its dependent work in https://github.com/opentdf/platform/pull/321 are merged in, there will be platform support for matching of Subjects to Attribute Values through Subject Mappings (also known as entitlements) via external fields and values (SubjectProperty in the protos) like those found in an idP or external User Store. 

It is understood that the Attributes and Policy services should serve as CRUD for storage of policy objects, and that interpretation of those objects is the concern of other services. Relevant to this performance note is the separation of concerns that Attributes Service will do a wide and liberal lookup to find any potential match of a Subject Mapping referencing one of the provided External Field / Value pairs provided when matching in a single Condition, with only the slightest filtering for IN/NOT_IN in the matching.[^1] From those liberally matched Subject Mappings, the client service (most often Authorization Service) will maintain the responsibility of interpreting the potential matches into informed Policy Decisions with the boolean logic and multiples of Conditions, ConditionGroups, and SubjectSets within a given match. Client PEPs or other services should rely on Authorization Service for trustworthy results on the Attribute Values entitled to a Subject. 

There are known performance concerns with the current approach that are increasingly likely to be experienced as the number of Subject Mappings and Subject Condition Sets scales. 

The current approach (brought in by https://github.com/opentdf/platform/pull/347):

1. uses a SQL subquery on the `subject_condition_set` table, which means O(n^2) on that table
2. accesses the column's stored JSONB [2]
2. iterates through the Subject Sets array's Condition Groups
3. iterates through each Condition Groups' individual Conditions
4. builds the query such that every SubjectProperty provided in the RPC is matched against the Condition's field, values array, and operator match

While there is a potential for a bottleneck caused by the Attributes Service liberal lookup matching too many Subject Mappings for performant processing by the Authorization Service, that is not the concern of this issue, which is focused on the performance time to query at scale.

### Potential paths forward

> [!NOTE]
> :warning: These are the current obvious paths forward, but may not be best. Further time for exploration should be given to Option 1 and 3 before a decision is finalized as they may have simple and obvious feasibility once time is allotted to explore.

#### Option 1. SPIKE and invest more time attempting to optimize the SQL query

It's possible we could use something like a [Common Table Expression (CTE)](https://www.postgresql.org/docs/current/queries-with.html) to optimize the SQL.

* 🟢 Admins are generally very cautious
* 🟢 Cause strain on admins potential to reduce the lookup to O(n) from O(n^2) on the Subject Condition Sets table, which is huge
* 🟢 faster to explore, test, and implement
* 🟢 no additional maintenance cost or implementation changes
* 🔴 does not resolve any performance lag from querying keys/values within the stored JSONB, which may be significant or negligible
* 🔴 may not work; needs more time investment

#### Option 2. Move the JSONB tree structure into individual tables

We could create individual tables so that each Subject Set is a row, each Condition Group is a row, and each Condition is a row, all on independent tables that relate one to many down the tree with Foreign Keys.

* 🟢 definite would work to reduce Big O to `O(n)` instead of `O(n^2)` because the JOIN would be on the matched Conditions alone
* 🟢 potential of component reuse, so instead of storing Condition Groups that are often used in individual but different Subject Condition Sets, that sole row on the Condition Group table could reference multiple different Subject Sets
* 🔴 adds complexity to the platform admins and developers both would need to understand, and a large goal is to reduce complexity
* 🔴 more room for bugs and complexity of maintenance with more tables and more RPCs to support
* 🔴 less flexibility for iterative changes, like allowing Boolean AND/OR logic at the Subject Set or Subject Mapping level (changing how to interpret multiple Subject Sets or multiple Condition Groups)
* 🔴 will take time to build user-intuitive RPCs and durable data layer to power them

#### Option 3. Employ some kind of a "search term cache" of just the SubjectProperty fields

We could keep a list of the individual Condition's known `subject_external_field` names in a column of the Subject Condition Set table as a `varchar[]` to significantly reduce `n` in the `O(n^2)` lookup time to just Subject Condition Sets that are known to relate to one of the provided fields instead of every row on the Subject Condition Set table.

* 🟢 iterating through a `varchar[]` column at the top of the table should be able to be work with a CTE, unlike the questions around JSONB
* 🟢 it is expected that reads far outnumber writes, so any performance concerns about writes to the cached field names would be negligible in comparison
* 🔴 all the common concerns around cache consistency would need to be addressed
* 🔴 similar to the concern in footnote [^1], a single field name used very widely would eliminate any performance gain from this path forward

[^1]: The Attributes Service unfortunately must look at the `IN`/`NOT_IN` state of the Condition when matching to avoid potentially common extreme edge cases. For example, if a policy admin relies heavily on a very widely used external field name like `username` or `emailAddress` and `IN` rules, should the Attributes service query without filtering by recognizing the IN/NOT_IN scenario, it may return nearly every Subject Mapping in the database, which is not only unhelpful but has its own suite of follow-on concerns.

[^2]: It was decided to store the relation of Subject Sets > Condition Groups > Conditions in JSONB for a few reasons [documented with the migration]((https://github.com/opentdf/platform/blob/main/migrations/20240228000000_add_subject_condition_sets.md#:~:text=It%20is%20known,as%20a%20v1.)) and it is known that there is a need to iterate.

**Comment by jrschumacher** [comment]
We need to create an issue to run performance tests across the platform:

- KAS concurrency (under 3s)
- authorization caching of policy data (maybe needed)

**Comment by cassandrabailey293** [comment]
defer until doing benchmarking tests - https://github.com/virtru-corp/data-security-platform/issues/63
