### ISSUE TITLE
Implement token introspection in DPoP

### ISSUE THREAD

**Issue by mkleene** [opentdf/platform#409]
The validation of the binding between an access JWT and a DPoP JWT can be validated in two ways.
In the first [the thumbprint of the JWK is embedded in the `cnf` claim of the access token](https://datatracker.ietf.org/doc/html/rfc9449#section-6.1). 

In the second method, the [thumbprint of the JWK is retrieved from a token introspection endpoint](https://datatracker.ietf.org/doc/html/rfc9449#section-6.2). This introspection endpoint is available at the `.well-known/oidc-configuration` document
under the key `token_introspection`.

It's not completely clear to me how these methods relate to each other but a decent idea seems to be to

```mermaid

flowchart TD
    B{Does access token have a `cnf` claim?}
    B -- Yes --> F[Validate as DPoP]
    B -- No ----> C{Does token introspection endpoint exist?}
    C--Yes-----> D{Does token introspection endpoint return a `cnf` for the token?}
    C--No------>E[Validate as non-DPoP]
    D--Yes----->F[Validate as DPoP]
    D--No------>E
```

**Comment by biscoe916** [comment]
@mkleene Is this required for DPOP support? Trying to figure out where it lands in priority

**Comment by mkleene** [comment]
@biscoe916 no, it's not, depending on the auth provider. We can likely close this, especially given the way that we force customers to opt in to disabling DPoP. If a customer really wants DPoP then we will notice that their IdP uses token introspection to use it and we can scope the work. I'm not aware of any IdPs that use this method for producing bindings.

**Comment by strantalis** [comment]
@mkleene @biscoe916 I am going to close this for now then and we can reopen once we hit this issue.
