### ISSUE TITLE
OIDC configuration in opentdf.yaml set and read

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#427]
- Update example-opentdf.yaml to hold generic OIDC settings
- Update KAS to read settings https://github.com/opentdf/platform/blob/6c8fbeea1bbee1ad39350a6bec942835def366fe/services/kas/kas.go#L20
- Update entitlements to read settings https://github.com/opentdf/platform/blob/9df632ededaf3a2f363a702788d0077a7ac24ddb/internal/entitlements/pdp.go#L22
- Update examples to read settings https://github.com/opentdf/platform/blob/6c8fbeea1bbee1ad39350a6bec942835def366fe/examples/cmd/decrypt.go#L33
- Update authn settings https://github.com/opentdf/platform/blob/4c734bb11d6ba900d1d8118c8b9509f5c0d60d4a/example-opentdf.yaml#L46
- check .well-known endpoint

**Comment by strantalis** [comment]
@pflynn-virtru Is this resolved?
