### ISSUE TITLE
Need equivalent of 'Order' value for Attribute

### ISSUE THREAD

**Issue by patmantru** [opentdf/platform#433]
As encountered in PLAT-2950 work:

Previously there was a getOrder() method, this no longer exists on the Attribute object.

AC:
- Equivalent of the getOrder() method available by some means for Attribute objects

**Comment by biscoe916** [comment]
@jrschumacher @patmantru Is this still an issue?

**Comment by jrschumacher** [comment]
I believe @jakedoublev added hierarchy.
