### ISSUE TITLE
GetDecisions should all decisions in a request fail if one FQN lookup fails

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#492]
From a TODO here: https://github.com/opentdf/platform/blob/49320c718040fd4892c150c27ced1ad4fd37eed8/services/authorization/authorization.go#L76

CommentsL

I don't think so, but we may want to create an internal error object we can pass to the decision endpoint.

For instance if the resolution of an attribute is that of a value with an ANY_OF and another of its siblings is included then it would resolve true.

If it's a ALL_OF then it would resolve false.

If it's a hierarchy then the resolution is indeterminable.

If it's alone then it would resolve false since ANY_OF is false.

If it doesn't have a namespace or definition registered then it would resolve false.

**Comment by biscoe916** [comment]
I think the answer is that the entire request should fail in the event that one of the FQN look ups fail. My understanding is that if one fails, we don't have enough information to make an accurate access decision since we won't know if the failing FQN would resolve to an ANY_OF, or an ALL_OF.
