### ISSUE TITLE
Policy API: Extend error messaging with wrong parameter info to improve clarity and not mislead user.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#505]
**Overview:**
In some cases response error message looks misleading as it doesn’t contain specific parameter names which may cause wrong users perception. So it would be good to extend error messages with more detailed info e.g. wrong params info. 

E.g. case of AttributeService.CreateAttributeValue gRPC request complaining on wrong _**value**_ parameter while actually 'members' param value causes an error: 
------

**Steps to Reproduce:**
1. Run the backend server for the opened/platform (as described in the [Readme](https://github.com/opentdf/platform/blob/main/README.md)).
2. Create a Namespace and an Attribute.
3. Perform AttributeService.CreateAttributeValue gRPC request with filling next parameters: valid _id_ of existed attribute,  valid _value_ of String format, INVALID 'members' value of string format (while it should be uuid as per docs) .
4. Invoke the request and observe response.

**Actual Result:**
Request fails with “3 INVALID_ARGUMENT” code in response complaining on non-uuid format of the **_value_** parameter:
<img width="1278" alt="ExtendErrorMessage" src="https://github.com/opentdf/platform/assets/100794336/4c27884b-c187-4f3f-855f-63dfc695be79">

So it looks like _value_ param is wrong while actually _members_ value is wrong.

**Expected Result:**
Extend the error message with wrong param info so that user can clearly understand what is wrong in the request.

**Comment by jakedoublev** [comment]
I think this might be an error message issue @sievdokymov-virtru and actually stemming from invalid `members` in your example. Could you please let me know if you're able to reproduce using valid members? 

The following succeeds for me, where `e1536f25-d287-43ed-9ad9-2cf4a7698e5f` is one of the sample provisioned attribute ids and already exists in the DB. 
```bash
grpcurl -plaintext -d '{"attribute_id":"e1536f25-d287-43ed-9ad9-2cf4a7698e5f","metadata":{"labels":[{"value":"id","key":"quis esse do tempor"}]},"value":"VALUE123"}' localhost:8080 policy.attributes.AttributesService/CreateAttributeValue
{
  "value": {
    "id": "decfde39-fd1a-4959-aebe-c3d21b46d12b",
    "attribute": {
      "id": "e1536f25-d287-43ed-9ad9-2cf4a7698e5f"
    },
    "value": "value123",
    "active": true,
    "metadata": {
      "labels": {
        "quis esse do tempor": "id"
      }
    }
  }
}
```

The members should be valid, pre-existing value UUIDs as `[]string` [per the proto](https://github.com/opentdf/platform/blob/main/service/policy/attributes/attributes.proto#L137).

**Comment by sievdokymov-virtru** [comment]
@jakedoublev you're correct, with valid member(s) request passes successfully. Sorry for the inconsistency.

At the same time, existed message can mislead someone else with this "value parameter  => complain on value" state. Could we extend the error message to include affected parameter name for better clarity ('members' in our example)?

**Comment by jakedoublev** [comment]
I think that makes sense. Can you please update the issue to reflect the need for a better response message and the @opentdf/opentdf-policy can get it queued up with a priority unless it's something you'd like to update yourself?

**Comment by sievdokymov-virtru** [comment]
@jakedoublev Updated.

**Comment by jakedoublev** [comment]
This has been pulled in for fixing. If you'd like to contribute @sievdokymov-virtru, it should be a relatively minor update to improve this error message.

**Comment by suchak1** [comment]
Here is the ambiguous error message for reference:
https://github.com/opentdf/platform/blob/14305df714fc8cae9dab0edbaeab5b269e6111f9/service/internal/db/errors.go#L29

Here is an example of the error triggered by an invalid member uuid:
https://github.com/opentdf/platform/blob/14305df714fc8cae9dab0edbaeab5b269e6111f9/service/integration/attribute_values_test.go#L259-L263
