### ISSUE TITLE
SDK: well known configuration should be exposed via the SDK

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#563]
### Background

The SDK registrations [do not currently include the WellKnownService](https://github.com/opentdf/platform/blob/main/sdk/sdk.go#L30). This presents a challenge to downstream users, who must make an independently dialed call to the platform's well-known service to retrieve the `"platform_issuer": "http://localhost:8888/auth/realms/opentdf"` value. This value drives authentication as the OIDC token endpoint is further behind this endpoint. 

### Acceptance Criteria

1. The SDK exposes the WellKnownService
2. Any relevant SDK docs are updated

**Comment by biscoe916** [comment]
@jakedoublev Doing this work on a different PR. There's slightly more to this than adding the wellknown service, as it should also populate the token endpoint appropriately.  Let's keep the issue open, but close the attached PR. I'll try to get mine up by tomorrow.

**Comment by biscoe916** [comment]
If this is blocking anyone, I'll prioritize getting it out today.

**Comment by jakedoublev** [comment]
@biscoe916 I can keep the values hardcoded in `otdfctl` and remain unblocked on https://github.com/opentdf/otdfctl/issues/75 & https://github.com/opentdf/otdfctl/issues/105. It does block dynamically reading the values from the config, but that can definitely be punted a few more days.

**Comment by strantalis** [comment]
Resolved by https://github.com/opentdf/platform/issues/895
