### ISSUE TITLE
Undefined symbols when running the opentdf service according to the documentation/instructions

### ISSUE THREAD

**Issue by rsundaar1** [opentdf/platform#565]
After downloading the latest opentdf app, tried running "go run github.com/opentdf/platform/service provision keycloak". I see thefollowing errors:

# github.com/opentdf/platform/service/internal/security
service\internal\security\hsm.go:51:13: undefined: pkcs11.Ctx
service\internal\security\hsm.go:52:13: undefined: pkcs11.SessionHandle
service\internal\security\hsm.go:71:27: undefined: pkcs11.ObjectHandle
service\internal\security\hsm.go:73:26: undefined: pkcs11.ObjectHandle
service\internal\security\hsm.go:147:57: undefined: pkcs11.Ctx
service\internal\security\hsm.go:149:16: undefined: pkcs11.New
service\internal\security\hsm.go:160:39: undefined: pkcs11.Ctx
service\internal\security\hsm.go:168:33: undefined: pkcs11.Ctx
service\internal\security\hsm.go:208:38: undefined: pkcs11.Ctx
service\internal\security\hsm.go:346:64: undefined: pkcs11.ObjectHandle
service\internal\security\hsm.go:149:16: too many errors

**Comment by jakedoublev** [comment]
Thanks for opening this issue @rsundaar1! Are you still experiencing it if you pull the latest? This was likely fixed by some of the pulls around HSM and the crypto utilized.

**Comment by dmihalcik-virtru** [comment]
This is likely still an issue. We might need to add build tags to prevent 

We can do this by refactoring `hsm.go` so it uses a build tag, adding 

```go
//go:build hsm
```

to the top of the file, then adding another bit of code that lets it compile when the `hsm` tag is not set during `go build`.

**Comment by dmihalcik-virtru** [comment]
@rsundaar1 

To address the issue above you need to install a PKCS 1.1 compatible library, called in the code an HSM library. These libraries tend to be platform specific so for ease of development we generally use the [softHSM](https://www.opendnssec.org/softhsm/) library, which provides that API on top of openssl.

**Comment by dmihalcik-virtru** [comment]
People internally are often running into this, especially when trying to use platform/service as a library.

**Comment by dmihalcik-virtru** [comment]
This is merged as of https://github.com/opentdf/platform/pull/830 and should be available in 0.4.3 when we tag that
