### ISSUE TITLE
Entitlements Endpoint: Update to align with ADR 472

### ISSUE THREAD

**Issue by ttschampel** [opentdf/platform#567]
Update Entitlements Endpoint to Align with ADR #472  

The rough task list:

- Define entity resolution service interface (ERS)
- Move Keycloak IDP Plugin to a service implementing the ERS contract
- Move the JQ Custom Built-In Function to a Subject Mapping Built-In Function `resolve` encapsulating both the JQ Selector and condition evaluation currently residing in Rego.  
- Update the platform to use a single Core Rego file that consists of fetching the entity representation for a configured ERS endpoint and then passing to the new Subject Mapping resolve function
- Remove Keycloak specific inputs in OPA engine call.

**Comment by jrschumacher** [comment]
@jakedoublev anything we should consider for policy with regards to acceptance criteria?

**Comment by elizabethhealy** [comment]
i'm getting started on the third bullet `Move the JQ Custom Built-In Function to a Subject Mapping Built-In Function resolve encapsulating both the JQ Selector and condition evaluation currently residing in Rego.`
