### ISSUE TITLE
Policy API: No attribute definition ID existence validation on performing Update requests.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#569]
'0 OK' successful response is returned on performing Update entity requests (e.g. UpdateAttribute) if use non-existed id value (quite confusing since it doesn’t affect database and doesn’t provide proper feedback for an operation containing  e.g. id mistake)

**Steps to Reproduce**:
1. Run the backend server for the opened/platform (as described in the [Readme](https://github.com/opentdf/platform/blob/main/README.md)).
2. Create a Namespace and an Attribute.
3. Perform AttributeService.UpdateAttributeValue gRPC request with filling required parameters but use not existed id value.
4. Invoke the request and observe response.

**Actual Result**:
Request unexpectedly passes and returns “0 OK” success code in response which may mislead user:
<img width="1274" alt="WrongId" src="https://github.com/opentdf/platform/assets/100794336/fe96eca2-cca7-48eb-a4b2-6d558d6b54a0">

**Expected Result**:
Request should fail with “3 INVALID_ARGUMENT” response to give a feedback that irrelevant id was used and may require some corrections.

**Additional Info**:
id validation is performed properly e.g. on Deactivate Entity requests or when using parental entity ids in Create requests etc.

Correspondent JIRA issue: https://virtru.atlassian.net/browse/PLAT-3116

**Comment by jakedoublev** [comment]
When I run through this scenario, it appears this is now resolved. Please reopen if you're able to reproduce @sievdokymov-virtru.
