### ISSUE TITLE
Add an `audience` parameter for client credentials authentication

### ISSUE THREAD

**Issue by mkleene** [opentdf/platform#571]
Currently we specify the `audience` parameter when we provision keycloak. Other IdPs do things differently and may only issue access tokens for `audience`s that have been requested. e.g.
* [ory](https://www.ory.sh/docs/hydra/guides/audiences)
* [auth0](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow/call-your-api-using-the-client-credentials-flow)

I can't find this parameter listed in a spec. The closest thing I've found is [the `resource` parameter](https://www.rfc-editor.org/rfc/rfc8707.html#name-resource-parameter), but it seems that we should support this because certain IdPs require it.

To do so we need to add a new config option to the SDK to specify an `audience` (or `resource`, probably) that should be used when requesting an access token in the context of a client credentials flow.

**Comment by mkleene** [comment]
it doesn't seem like this is actually in the spec, if it's required for some providers then we might need to re-evaluate.

**Comment by mkleene** [comment]
this is not in a spec but seems important to support

**Comment by strantalis** [comment]
@mkleene Where are you saying this should be set and is this still an issue we need to triage?

**Comment by mkleene** [comment]
@strantalis I think that we might be able to avoid implementing this until we interact with scenarios + IdPs that require it. The two auth providers listed above allow this parameter to be set and I think that it governs that audience of the issued token.
