### ISSUE TITLE
Automate a newsletter with all the new features and enhancements

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#581]
As we continue developing new features and enhancements to the platform, OpenTDF contributors would benefit from a rollup newsletter helping them to keep up with the changes.

In alignment is our desire to increase community engagement and one way we hope to do this is via Github Discussions. These announcements would fit nicely in: https://github.com/orgs/opentdf/discussions/categories/announcements

---

Idea contributed by @c-r33d

**Comment by c-r33d** [comment]
As we create new releases it would be really cool to be able to have a workflow that will use some service that makes calls to an LLM to generate examples. This could be done by possibly analyzing the tests that were created in the release bundle, along with some semantical meaning which is derived from changelog/commit entries. I believe this will not only be helpful internally, but for developers outside of the organization.
