### ISSUE TITLE
Policy API: Ability to refer to existed entities by unique Name (as alternative to ID) to improve usability

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#585]
Consider ability to refer to existed entities by its unique Name as a distinct and easier to remember option for usage in Policy API calls. Seems like it could be solid usability improvement (addition and possible alternative to IDs usage).

E.g.:
- by 'name' for a namespace entities  
- by 'fqn' for an attribute
- by 'fqn(s)' for an attribute value etc.

**Comment by jakedoublev** [comment]
Related to https://github.com/opentdf/platform/issues/515 & https://github.com/opentdf/platform/issues/447
