### ISSUE TITLE
Policy API: Authorization with API-generated token is failed with “DPoP header is absent” error.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#606]
Policy API calls (both gRPC and HTTP) receive "Unauthorised" error response when using API generated access_token (issued by request to http://localhost:8888/auth/realms/opentdf/protocol/openid-connect/token) for authorisation.
It complains on problem with DPOP validation: “msg="failed to validate token" error="got 0 dpop headers, should have 1"”

E.g.:
<img width="1221" alt="AuthFailed" src="https://github.com/opentdf/platform/assets/100794336/f93486d4-97d8-4d99-bb15-80edcf4f2fc0">

Token generated by this [suggestion](https://virtru.slack.com/archives/C0682KDGQPQ/p1710350355921279):
<img width="1234" alt="Token" src="https://github.com/opentdf/platform/assets/100794336/f7332588-f6aa-4089-8aa1-032fe49b6a68">

Reproducible with locally deployed Platform which uses example env setup with Auth enabled (as described in the [Readme](https://github.com/opentdf/platform/blob/main/README.md))

**Additional Info**:
Currently DPoP-compatible token can only be generated using SDK as per @mkleene (using https://github.com/opentdf/platform/blob/27354988d6ef9b3616d3b60e76fa63b16f68f195/sdk/internal/oauth/oauth.go#L137-L167).
And backend validates only DPoP tokens.

**Expected Result**: 
It is possible to generate DPoP-compatible token using direct API call (is it possible to use specific DPoP params?).

Also there is ongoing discussing regarding ability to optionally disable DPoP validation. It could be possible workaround if it doesn't raise additional security concerns.  

-----

DPoP-related issues: #566, #593

**Comment by mkleene** [comment]
https://github.com/opentdf/platform/pull/617 should resolve this

**Comment by sievdokymov-virtru** [comment]
Addressed by ability to disable DPoP verification introduced in #617. Verified/Fixed.
Closing as Done.
