### ISSUE TITLE
Unable to run the platform scripts in a Windows environment

### ISSUE THREAD

**Issue by rsundaar1** [opentdf/platform#616]
There init-temp-keys.sh needs to be in Unix like commandline. Gitbash seems to work for this if you set the environment variable "export MSYS_NO_PATHCONV=1". Also need to set " CGO_ENABLED=1" in windows. This may also be the case if you run wsl or virtualbox. May need to install mingw64 for gcc. These steps helped me move forward but not without many hours of struggle. Would be good to document these steps.

**Comment by jrschumacher** [comment]
@rsundaar1 thank you for contributing to the betterment of OpenTDF! We're processing your issue and will add it to our roadmap.

**Comment by dmihalcik-virtru** [comment]
I'll look into disabling the HSM library by default using build tags. There are likely other issues with windows, however, so this probably won't be enough (e.g. lots of scripts assume bash is present)

See https://github.com/opentdf/platform/issues/565
