### ISSUE TITLE
ADR: Open Policy Agent (OPA) removal

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#630]
# Open Policy Agent removal

## Context and Problem Statement
Currently, we use [OPA](https://www.openpolicyagent.org) for our entitlement PDP.

<img width="998" alt="Screenshot 2024-04-22 at 2 25 22 PM" src="https://github.com/opentdf/platform/assets/43211074/3f8c904d-34e9-40fa-b169-c66eb905c913">

This is the next iteration, soon-to-be-merged.  Note most logic is removed from .rego, basically it is just glue at this point.

<img width="636" alt="Screenshot 2024-04-24 at 11 21 18 AM" src="https://github.com/opentdf/platform/assets/43211074/1ea3bc18-686d-4ec3-b3b4-e9f9d9e6448f">

### Relevant ADR
Entitlement Policy Deployment Model https://github.com/opentdf/platform/issues/472
Configuration Service https://github.com/virtru-corp/adr/blob/main/docs/decisions/ar-8-config-service-v2.md

## Decision Outcome
- 📜 No change
  - Keep OPA
  - Re-evaluate after upcoming major milestone

### Decision Notes
- 🟩 Infinite flexibility in entitlement PDP
- 🟨 More data points needed - this will come after the next major milestone
- 🟨 Support should be like other sub-system integrations, ex. database, IdP
- 🟥 Developers' velocities will be impacted when working around OPA

## Decision Drivers
- OPA development challenges
  - type conversion
  - built-in development
  - testing
  - small rego codebase < 50 loc
- OPA customer challenges
  - non-support if changed
- OPA capabilities
  - Federation of policies
  - Policy signing
- OpenTDF subject mappings solution
- Possible performance bottleneck (not enough data)

## Considered Options
- Remove OPA library
- Optional OPA library
- Optional OPA service integration
- Support and Keep OPA

###  ⚖️ Remove OPA library

Create a pure Go implementation of the Entitlement PDP.  Mimic what is done with [Access PDP](https://github.com/opentdf/platform/blob/main/service/internal/access/pdp.go)

* 🟩 Developers happy
* 🟨 Moves integration point to Entity Resolution Service (ERS)
* 🟥 One less integration point

### ⚖️ Optional OPA library

Create a pure Go implementation of the Entitlement PDP.
Leave OPA-Entitlement PDP.
Create a configuration to enable.
```
authorization:
  entitlement:
    # native Golang
    pdp: default
    # unsupported OPA
    pdp: opa
```

### ⚖️ Optional Entitlement PDP Service integration with OPA example

Create a pure Go implementation of the Entitlement PDP.
Remove OPA-Entitlement PDP.
Create a configuration to enable.
```
authorization:
  entitlement:
    # native Golang
    pdp: default
    # unsupported
    pdp: remote
    url: https://pdp-opa-service/entitlement
```

The design could be similar to the v1 entitlement PDP https://github.com/opentdf/backend/tree/main/containers/entitlement-pdp

* 🟩 Integration point with other services than OPA is doable.
* 🟨 Previous design
* 🟥 Supported?

### ⚖️ Support and Keep OPA

* 🟩 Supported!

**Comment by jrschumacher** [comment]
Great work @pflynn-virtru. I think you are calling out some important trade-offs. It seems that if we chose Option 1 we could cue up additional work to implement Option 3. Would this enable customers to hook into their existing authorization service like [Strya](https://www.styra.com), [Permit.io](https://permit.io), or [AuthZed](https://authzed.com)?

**Comment by ttschampel** [comment]
I think we either do nothing or option 1. 

It sounds like OPA is causing to much friction at the moment for our developers; if this is true then option 1 seems like the only choice.

We have not fully implemented and tested a full set of scenarios E2E flows through the Authorization Service RPCs; given this current state I think only option 1 really makes sense.  The ERS will capture the complexity and customization for near term deployments.  Until we fully understand what should be easily configurable (ABAC auth, entitlements, entity resolution, etc.)

An example would be someone has their own entitlements service already.  Does the entitlement service speak ABAC and the Attribute space within the deployment?  Should those entitlements be transformed via subject mappings?  At a certain point someone could just use the existing spec and plugin in their own RPCs per the protobuf service apis.

**Comment by damorris25** [comment]
I'd advocate doing nothing until we have a fully working platform that is stable, reliable, and well-documented. At that stage, iterating on improvements to the platform would make sense.

**Comment by pflynn-virtru** [comment]
Added last minute option: "Support and Keep OPA"
