### ISSUE TITLE
package has reserved word "go" and "/"

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#648]
The package `protocol/go` contains a reserved word in Golang - which is "go".

Also, "/" should not be in package names.

Desired actions:
- Rename package

**Comment by strantalis** [comment]
@dmihalcik-virtru I wonder if we should just bite the bullet and make this change. I think we held off on it when we renamed stuff because of how impactful it might be.

**Comment by strantalis** [comment]
As a first step remove `go` from `protocol/go`.
