### ISSUE TITLE
Either remove RESTFul KAS support or expose it in the SDK

### ISSUE THREAD

**Issue by mkleene** [opentdf/platform#650]
We currently have support for RESTFul KASs in the golang SDK. This functionality is not exposed to end users at the moment. We should either remove this functionality or expose it to users.

Having support for RESTFul KASs makes certain kinds of compatibility testing possible, which could be useful.

On the other hand it would be easier to remove the code and simplify how we interact with a KAS.

**Comment by strantalis** [comment]
@mkleene The whole platform exposes a gRPC and Restful interface. Where do we support the rest interface for kas in the go sdk?

**Comment by patmantru** [comment]
If the rest support isn't directly in the kas code, tis could possibly be addressed with a gateway of some sort, even one just in place specifically for interoperability/compatibility testing.

Or we can decide the cost/benefit math doesn't work out, and decide to not have direct rest support.

**Comment by mkleene** [comment]
> [@mkleene](https://github.com/mkleene) The whole platform exposes a gRPC and Restful interface. Where do we support the rest interface for kas in the go sdk?

It's in the `AuthConfig` class. It's currently exercised in the tdf_test code with a mocked out web server.

**Comment by jrschumacher** [comment]
By exposing it in the SDK are you saying that you want some function (i.e. `Rewrap()`) to use an HTTP transport rather than gRPC? I could see how this is important for [Web without since gRPC](https://grpc.io/blog/state-of-grpc-web/).

**Comment by strantalis** [comment]
@mkleene What is the authconfig used for? I always thought that would go away and was temporary.

**Comment by arkavo-com** [comment]
We are using the KAS restful endpoints in our iOS app.  The app uses https://github.com/opentdf/client-cpp

If you remove, please update client-cpp or create client-objc ;)

**Comment by strantalis** [comment]
The GO SDK will only support grpc interaction with KAS. We can reopen if there is a use case to support http rest interface.
