### ISSUE TITLE
WIP: ADR Attribute lifecycle

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#661]
# Attribute lifecycle

## Goal 

Guarantee the Platform can handle identified, supported attribute lifecycles. 

## Problem

An attribute can be in a undefined state, and used in an unidentified use case that results in a fail-closed (hopefully) result.

## Showcase

TODO show the different areas that use Data Attributes and the process of creating, assigning, enforcing, sharing, and deprecating.

Areas:
- Highly-controlled, well-defined, well-known, centralized - Military
- Controlled, loosely-defined, less-known, centralized - Business
- Free-form, ever-changing, unknown, distributed  - Social
TODO expand

TODO Provide diagrams: State, Activity, Sequence

## Decision Outcome
TBD - Product and Architecture decisions needed

## Decision Drivers
- Documented
- Enforced
- Messaged
TODO

## Considered Options
- Support all identified
  - via complex configuration
  - via custom plugins / handlers
- Support only selected
  - via simple configuration
  - hardcoded

**Comment by strantalis** [comment]
@pflynn-virtru Does this still need to flushed out?

**Comment by jrschumacher** [comment]
Seems like this is very niche and shouldn't be considered as part of the open. Does our existing framework enable users to take the platform and extend it to implement this themselves?
