### ISSUE TITLE
ADR: service health check roll up

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#700]
## Problem

As part of the work to enable scoped database connections we introduced a defect within the healthcheck #699. This issue revealed that services need to own their healthcheck and our main platform needs to roll these up as part of a high level healthcheck. 

## Solution

Implement an optional parameter as part of the registration called `healthz`. This parameter will enable services to append their own healthcheck process as part of a roll up within the platform healthcheck. 

When services require database connections it will be their burden to implement a healthz endpoint that pings their database connection to make sure it's healthy.

**Comment by strantalis** [comment]
At a high level what we want is for [this](https://github.com/opentdf/platform/blob/main/service/health/health.go) health service to call out to those registered services healthz function that were registered. 

If they don't register a healthz function we should return a status of `unknown`. 

We probably can mimic what I had originally [setup](https://github.com/opentdf/platform/blob/main/service/pkg/serviceregistry/serviceregistry.go#L34) for WellknownConfig. Allowing the service to register something like `HealthzRegistration(namespace string, healthz func()) error`

**Comment by jakedoublev** [comment]
> At a high level what we want is for the [health service](https://github.com/opentdf/platform/blob/main/service/health/health.go?rgh-link-date=2024-05-01T16%3A49%3A44Z) to call out to a registered services healthz function that is registered.
> 
> If they don't register a healthz function we should return a status of `unknown`.

What if `healthz` is broken out into separate liveness/readiness concerns? From the perspective of the rolled up healthz service, if a service is registered and the platform is running, doesn't that mean it's inherently `live` and not `unknown`? Maybe just the readiness probe is what needs to be able to be registered? `HealthzReadinessRegistration(namespace string, readiness func()) error`.

I wonder what the value is in requiring a liveness check defined separately from registration when it seems like successful registration to the running platform instance without liveness couldn't happen?

**Comment by strantalis** [comment]
That makes sense to me. I don't think a service needs a liveness check. 

Also if a service returns an error I guess we need to mark the overall readiness of the platform down? This might get complicated the more I think about it because policy can operate fine without kas or authorization service being operational. But maybe this is where we push for services to be split out in the future.

**Comment by jakedoublev** [comment]
> Also if a service returns an error I guess we need to mark the overall readiness of the platform down? This might get complicated the more I think about it because policy can operate fine without kas or authorization service being operational. But maybe this is where we push for services to be split out in the future.

Agreed. If the platform instance is running multiple services, those services need to all be ready for the platform to be ready. The extreme scenarios are fully modular deployment:
```
platform_instance_A -> running policy
platform_instance_B -> running authorization service
platform_instance_C -> running KAS

A's healthcheck should be ready if policy is ready, B's if auth svc is ready, C's if KAS is ready
```

On the other side would be a single platform instance running every service, in which one of the services going down is indeed catastrophic with a failure of the platform to be ready to perform its duties.

```
platform_instance_A -> running policy, authorization, KAS

Any one of the three services going down has catastrophic effects to the platform's functionality.
```

 I think readiness should be all or nothing for a platform instance running whatever services it's running?

**Comment by strantalis** [comment]
> I think readiness should be all or nothing for a platform instance running whatever services it's running?

Yep agree. I am going to line up some work so we can get started on this as the health check is broken today and is something we need.

**Comment by strantalis** [comment]
Tracking issues

- #726
