### ISSUE TITLE
Enable developers to fetch the list of attributes which the current user has access to

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#705]
To build PEPs with rich UX, developers need the ability to get the list of attributes that the user has access to. This feature enables PEPs to only allow creating TDFs with attributes to ensure the data created is accessible.

**Comment by jakedoublev** [comment]
Blocked by https://github.com/opentdf/platform/issues/644

**Comment by strantalis** [comment]
@jrschumacher @jakedoublev Is this just a get entitlements call to determine which attributes a user has access to?

**Comment by strantalis** [comment]
@jakedoublev If scopes is empty we should just return all entitlements for a user. At least thats how I would expect it to work. 

I don't fully understand why we error if scopes is empty. Do you know if we even did performance tests against this path?

**Comment by jrschumacher** [comment]
No I don't think we have with the latest.

**Comment by jrschumacher** [comment]
The performance concerns seem related to the algorithmic complexity, as documented in #365. However, we could allow it and just document that there might be performance issues with X number of subject mappings based on our performance tests.

**Comment by jrschumacher** [comment]
We've decided not to implement this within OpenTDF at present.
