### ISSUE TITLE
Error when performing decrypt with CLI and Platform examples

### ISSUE THREAD

**Issue by pacog1994** [opentdf/platform#739]
### Problem

There seems to be an issue with the decrypt logic when using the CLI or Examples in platform. I am currently getting an error message making a request to KAS and that I am unauthenticated.

 After debugging a little bit, the issue looks like it's coming from the SDK. 

If someone help me debug this that would be great.

### **./otdfctl decrypt**
![image](https://github.com/opentdf/platform/assets/15972323/f9bdcb2b-83d2-40c9-9744-84e97017be51)

### **./examples decrypt**
![image](https://github.com/opentdf/platform/assets/15972323/96ca99ce-4fd4-40b3-87ad-59a10c1eab13)

### **current git commit**
![image](https://github.com/opentdf/platform/assets/15972323/44a1fa4b-c136-47d8-9f23-ba3137fcc533)

### **opentdf.yaml**
```
logger:
  level: debug
  type: text
  output: stdout
# DB and Server confgurations are defaulted for local development
db:
  host: opentdfdb
#   port: 5432
#   user: postgres
#   password: changeme
services:
  kas:
    enabled: true
  policy:
    enabled: true
  authorization:
    enabled: true
    url: http://keycloak:8888
    client: "tdf-entity-resolution"
    secret: "secret"
    realm: "opentdf"
    legacy: true
server:
  auth:
    enabled: true
    enforceDPoP: false
    enforceDpop: false
    audience: "http://localhost:8080"
    issuer: http://keycloak:8888/auth/realms/opentdf
    policy:
      ## Default policy for all requests
      default: #"role:readonly"
      ## Dot notation is used to access nested claims (i.e. realm_access.roles)
      claim: # realm_access.roles
      ## Maps the external role to the opentdf role
      ## Note: left side is used in the policy, right side is the external role
      map:
      #  readonly: opentdf-readonly
      #  admin: opentdf-admin
      #  org-admin: opentdf-org-admin

      ## Custom policy (see examples https://github.com/casbin/casbin/tree/master/examples)
      csv: #|
      #  p, role:org-admin, policy:attributes, *, *, allow
      #  p, role:org-admin, policy:subject-mappings, *, *, allow
      #  p, role:org-admin, policy:resource-mappings, *, *, allow
      #  p, role:org-admin, policy:kas-registry, *, *, allow
      ## Custom model (see https://casbin.org/docs/syntax-for-models/)
      model: #|
      #  [request_definition]
      #  r = sub, res, act, obj
      #
      #  [policy_definition]
      #  p = sub, res, act, obj, eft
      #
      #  [role_definition]
      #  g = _, _
      #
      #  [policy_effect]
      #  e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
      #
      #  [matchers]
      #  m = g(r.sub, p.sub) && globOrRegexMatch(r.res, p.res) && globOrRegexMatch(r.act, p.act) && globOrRegexMatch(r.obj, p.obj)

  grpc:
    reflectionEnabled: true # Default is false
  cryptoProvider:
    hsm:
      enabled: false
      pin:
    standard:
      rsa:
        123:
          privateKeyPath: /keys/kas-private.pem
          publicKeyPath: /keys/kas-cert.pem
        456:
          privateKeyPath: /keys/kas-private.pem
          publicKeyPath: /keys/kas-cert.pem
      ec:
        123:
          privateKeyPath: /keys/kas-ec-private.pem
          publicKeyPath: /keys/kas-ec-cert.pem
  port: 8080
opa:
  embedded: true # Only for local development
```

**Comment by pacog1994** [comment]
Update: 

It's also important to note we are using Ubuntu for our environment. Here is the settings:

![image](https://github.com/opentdf/platform/assets/15972323/02ed2da5-d869-4a3f-b827-f2e91e2e9e73)

**Comment by jrschumacher** [comment]
@pacog1994 With the CLI did you authenticate prior to running decrypt?

**Comment by pacog1994** [comment]
Hi @jrschumacher, yes I ran the command `./otdfctl auth client-credentials --client-id opentdf --client-secret secret` and was able to authenticate.

**
![image](https://github.com/opentdf/platform/assets/15972323/0f28f36e-9e8f-4eaa-9683-6b1bfa7be95c)
**

Here's a screenshot to confirm

**Comment by jrschumacher** [comment]
Ah, we are aware of a CLI issue with *nix https://github.com/opentdf/otdfctl/issues/153. The linked issue includes some linked documentation about what is needed to get the keyring working. We haven't tested this yet.
