### ISSUE TITLE
platform ci: Add tests with java, cpp, web, and other downstream consumers

### ISSUE THREAD

**Issue by dmihalcik-virtru** [opentdf/platform#765]
These non-go libraries are implemented in other repositories to make it easier to build and separate work streams. However, this means they often discover regressions before we see them here. 

- We support cross-testing of TDF files where they are created with SDK A and tested with head and most recent release of all other clients (C++/python, javascript/web, and java) v. go
- We support service operations where possible

**Comment by cassandrabailey293** [comment]
this work is being tracked by an issue int he tests repo: https://github.com/opentdf/tests/issues/151

Closing this issue as duplicate.
