### ISSUE TITLE
Support claims entity type in opa/ERS

### ISSUE THREAD

**Issue by elizabethhealy** [opentdf/platform#788]
Enable the claims entity type in opa. It should not call ERS when the entity type is claims but rather should evaluate the subject mappings on the claims themselves. (I believe this is the expected behavior for this flow.)
It should be assumed claims is a type that can be parsed/queried by jq.

**Comment by elizabethhealy** [comment]
should help solve https://github.com/opentdf/platform/issues/785

**Comment by jrschumacher** [comment]
> It should be assumed claims is a type that can be parsed/queried by jq.
Do we need full jq support, or could we keep it simple and only support object dot-notation? I have no opinion if we use a jq compliant library under the hood, but limiting what we advertise will reduce complexity and cost less to maintain.

**Comment by elizabethhealy** [comment]
@jrschumacher im fine either way, i think dot notation is probably simpler and easier to support, or maybe some variation of dot notation that also supports like like item1.item2[*]

**Comment by jrschumacher** [comment]
@elizabethhealy is this completed or should we reopen?

**Comment by elizabethhealy** [comment]
we should reopen, i think there was another ticket issue linked to this as well, ill find it

**Comment by elizabethhealy** [comment]
relates to https://github.com/opentdf/platform/issues/785
