### ISSUE TITLE
go logging: Have some standards for logging

### ISSUE THREAD

**Issue by dmihalcik-virtru** [opentdf/platform#804]
Alternatives:

1. prefer `LogAttrs` for efficiency
2. Use custom logger type (platform.logger) to enable ease of `Audit` events. Prefer using Context and Attr structs.
3. Use default logger with custom Level and no requirements.

---
## LogAttrs

- https://pkg.go.dev/log/slog#hdr-Attrs_and_Values
- https://github.com/uber-go/zap?tab=readme-ov-file#performance

How it looks:

```go
import (
	"log/slog"
	"time"
	"github.com/platform/service/audit"
)

...

func x() {
	slog.LogAttrs(
		ctx,
		audit.Level,
		"x function started",
		slog.Time("now", time.Now()),
	)
}
```

## Custom Logger

> Move internal/logger/logger.go to service/logger/logger.go
> Update linter to look for use of default logger or other brand of logger and block them.

## No Rules

> Generate a custom handler that logs certain levels as audit or when various attr/context matchers are hit.
> Register custom handler at service start

**Comment by jrschumacher** [comment]
Are you suggesting we use this syntax `logger.LogAttrs(ctx, slog.LevelInfo, "hello", slog.Int("count", 3))` rather than `slog.InfoContext(ctx, "hello", slog.Int("count", 3))`?

What kind of efficiency gains do we get? Seems that this could prove challenging to enforce.

**Comment by dmihalcik-virtru** [comment]
It looks like the efficiency gains are minimal. [zap maintains a performance comparison](https://github.com/uber-go/zap?tab=readme-ov-file#performance) and it looks like we only save 2 allocs (out of about 4x the number of attributes we allocate in a line).
