### ISSUE TITLE
init-temp-keys.sh creates ECDSA key instead of ECDH

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#836]
Go `x509.ParsePKCS8PrivateKey(block.Bytes)` is interpreting  `kas-ec-private.pem` as ECDSA.  To force it to parse to ECDH you can use `X25519`

```
openssl genpkey -algorithm X25519 -out privatekey.pem
```

change will be here https://github.com/opentdf/platform/blob/main/.github/scripts/init-temp-keys.sh#L69

**Comment by pflynn-virtru** [comment]
see https://github.com/opentdf/platform/blob/9374f044621936cbf40ff7b9913a68e289059219/lib/ocrypto/ec_key_pair.go#L122
ConvertToECDHPrivateKey

**Comment by pflynn-virtru** [comment]
if you try to create an X.509 certificate using an X25519 private key, you will encounter this error because X25519 keys are used for key exchange but not compatible for certificate signing which requires signature algorithm.
More specifically, X25519 key type is used for Diffie-Hellman key exchange in ECC (Elliptic Curve Cryptography), but it is not supported for signing an X.509 certificate.

**Comment by pflynn-virtru** [comment]
We need a Diffie-Hellman key to do key exchange.  We can't create a certificate, so this will also address the issue https://github.com/opentdf/platform/issues/678

**Comment by strantalis** [comment]
@pflynn-virtru We are forcing it to ECDH 

https://github.com/opentdf/platform/blob/9374f044621936cbf40ff7b9913a68e289059219/lib/ocrypto/ec_key_pair.go#L124-L127

https://pkg.go.dev/crypto/ecdsa#PrivateKey.ECDH

Are we getting some type of error there?
