### ISSUE TITLE
SDK creates expensive key material every operation

### ISSUE THREAD

**Issue by imdominicreed** [opentdf/platform#846]
SDK creates 2048 bit RSA keys for the KAS Client and IDP token exchange on every request.

This causes a high overhead on every request. Here is the tracing on a Decrypt. As you can see, 95% of the decrypt time is creating key material. It would be able to set it manually and/or rotate automatically in the background. 
![image](https://github.com/opentdf/platform/assets/13471482/85c98c6f-ecdc-4ee6-a2a8-d02fe37cdeef)

**Comment by mkleene** [comment]
https://github.com/opentdf/platform/issues/587 is a pretty similar issue and would solve this as well, except for the rotation part.

**Comment by jrschumacher** [comment]
In addition supporting ECC for ephemeral keys would add a nice performance boost.

**Comment by dmihalcik-virtru** [comment]
One solution is to instead cache (and possibly expose in a limited way) the internal `KASClient` struct. It looks like for each `unwrap` method we create a new one, which means creating a new encryption key (called `asymDecryption` in the go code, and `ephemeral key` in the javascript code). The DPoP key similarly is tied to the IdP/OAuth/OIDC client, and likely indicates that we should cache this, too

**Comment by imdominicreed** [comment]
to follow up on this, another (very slightly, takes about 3ms on my machine) is https://github.com/opentdf/platform/blob/main/sdk/auth/token_adding_interceptor.go#L123 does a dpop token needs to be created every rpc request. but just wanted to bring it up.

this is closer to session management rather than this exact issue

this issue can probably be closed, and maybe another one related to session management
