### ISSUE TITLE
ADR: Obligation - Add support

### ISSUE THREAD

**Issue by ttschampel** [opentdf/platform#874]
# Background

An Obligation defines a requirement that should be fulfilled by a requesting `ENVIRONMENT` type Entity for a given Resource.  For example:  Watermarking is an Obligation of a requesting party before releasing access to "Trade Secret" data.

Obligations are currently unimplemented and mostly un-modeled.  The Decision RPC within Authorization Service currently contains the only reference to the obligations as part of the required obligations in a decision response.

# Problem

A flexible obligation design is needed to fit into the current ABAC model to both define and enforce obligations as part of policy decision enforcement:

- allow data owners to individually describe obligations per policy (per piece of data)
- allow policy authors to define obligations given a data policy (~ a set of data attributes)
- allow scoping of obligations to specific entities  

## Decision Outcome

Obligations as Attributes + Obligation Policy Mapping

- Obligations are modeled as Attribute Values, like “data” attributes.
- Obligations to be inferred via  a TBD policy object (Resource Mappings or TBD new object)  and used by the decision endpoint to get implied obligations
  - Input = Attribute Values[] (from the data policy)
  - Output = Attribute Values[] representing  obligations
- Obligations may be explicitly supplied by the data creator by adding them to the data policy (e.g. add watermarking by email)
- Obligations Attribute Values are added as an additional "derived obligation" attribute set prior to invoking the AccessPDP.  
- AccessPDP remains effectively the same; it still receives a list of "data attributes".  Now this list may have been enriched by the obligation policy mapping or explicitly added by a data owner (see above 2 bullets)

The use of different attribute/attribute values are encouraged to distinguish between those attributes that are meant ONLY for NPE obligations controls.  

TBD policy object:  It is preferred to use the existing ResourceMappings Policy Objects; but some updates would probably be required:

- add Attribute Value in addition to free-text terms?
- allow for more than one mapped attribute value to support multiple required obligations?

### Example Flow - Explicit Obligation Sequence Flows

The data owner has added an obligation directory to the data policy of Document A for watermarking (drm:watermarking) as well as a Confidential IP entitlement requirement (ip:confidential).

The primary flow shows Bob logging into  WebApp A where Bob is entitled to **ip:confidential** and the webapp is entitled **drm:watermarking**; because Bob has logged into WebApp A which has watermarking drm controls he is permitted to decrypt Document A.

In the alternate flow, Bob is logging in directly with no drm controls entitled.  Therefore the key request is denied.

```mermaid
sequenceDiagram
    participant bob as Bob
    participant client1 as WebApp A
    participant idp as IDP
    participant kas as KAS
    participant asvc as Authorization Service
    participant accesspdp as AccessPDP
    participant opm as Obligation Policy Mapping
    participant epdp as Entitlement PDP 

    bob->>+client1: login
    client1->>idp: authenticate
    idp->>client1: return access token
    Note over bob,client1: Document A is a TDF:<br>Policy:<br>[drm:watermarking,<br>ip:confidential]
    bob->>client1: decrypt Document A
    client1->>kas: request decrypt [DocumentA Policy + JWT]    
    kas->>asvc: GetDecisionsByToken[JWT,Policy]
    asvc->>opm: GetObligations(Policy)
    Note over asvc,opm: No additional obligations mapped
    opm->>asvc: []
    asvc->>epdp: getEntitlements
    epdp->>asvc: return entitlements[]    
    asvc->>asvc: resource attributes = <br>obligations + data attribute
    asvc->>accesspdp: get decision(entitlements, resource attributes)
    Note over accesspdp,asvc: Access is permitted b/c WebAppA is entitled to<br> drm:watermarking and Bob is entitled to ip:confidential
    accesspdp->>asvc: permit
    asvc->>kas: return permit decision with drm:watermarking obligation
    kas->>client1: return key + obligation
    client1->>client1: decrypt
    alt No client / Does not meet obligations        
        bob->>+idp: Login
        idp->>client1: return access token
        bob->>kas: decrypt Document A
        kas->>asvc: GetDecisionsByToken[JWT,Policy]
        Note over asvc,opm: Duplicate steps snipped
        Note over accesspdp,asvc: Access is denied, Bob is not entitled to drm:watermarking 
        accesspdp->>asvc: deny
        asvc->>kas: return deny decision
        kas->>bob: return error code
    end
```

### Example Flow - Policy Mapped Obligations

Similar to the above flow except the data policy for Document B only contains ip:confidential.  However an administrator as created a policy mapping for ip:confidential resources to required drm:watermarking obligations.   

The main difference from the above flow is that the policy mapping step returns a new resource attribute used for the AccessPDP decision.

```mermaid
sequenceDiagram
    participant bob as Bob
    participant client1 as WebApp A
    participant idp as IDP
    participant kas as KAS
    participant asvc as Authorization Service
    participant accesspdp as AccessPDP
    participant opm as Obligation Policy Mapping
    participant epdp as Entitlement PDP 

    bob->>+client1: login
    client1->>idp: authenticate
    idp->>client1: return access token
    Note over bob,client1: Document B is a TDF:<br>Policy:<br>[ip:confidential]
    bob->>client1: decrypt Document B
    client1->>kas: request decrypt [DocumentB Policy + JWT]    
    kas->>asvc: GetDecisionsByToken[JWT,Policy]
    asvc->>opm: GetObligations(Policy)
    Note over asvc,opm: A policy object maps ip:confidential->drm:watermarking
    opm->>asvc: [drm:watermarking]
    asvc->>epdp: getEntitlements
    epdp->>asvc: return entitlements[]    
    asvc->>asvc: resource attributes = <br>obligations + data attribute
    asvc->>accesspdp: get decision(entitlements, resource attributes)
    Note over accesspdp,asvc: Access is permitted b/c WebAppA is entitled to<br> drm:watermarking and Bob is entitled to ip:confidential
    accesspdp->>asvc: permit
    asvc->>kas: return permit decision with drm:watermarking obligation
    kas->>client1: return key + obligation
    client1->>client1: decrypt
```

**Comment by jakedoublev** [comment]
@ttschampel In this proposal does defining obligations that are `scoped the same way as “data” attributes` mean effectively Namespace -> Parent -> Child, or does it mean there are also the 3 Attribute Definition rules on them? If there are no rules on them or an understanding that every obligation is either `anyOf` or `allOf`, is there a requirement that they take the same form as data attributes and could not be instead `https://name.space/oblg/<parent>/value/<child>` for clarity?

In either case, it seems like a platform administrator would want to define a series of potential obligations and map them to attributes across their policy, reusing for example `drm:watermarking` across multiple attribute definitions. Does that also mean some values on a single definition might have `ip:confidential` and others might not within the same definition? Resource Mappings are not currently shared across multiple attribute values (just one), so that might indicate a new kind of relation for obligations, though we can keep thinking about that.

**Comment by ttschampel** [comment]
I think scope is an artifact from (the now defunct) Attribute Value Scoping ADR.  I just updated the text to remove that.  

Obligations are attribute values; so I think those obligation mappings would be data attribute value -> 0..N obligation attributes. 

Agree on resource mappings, this use case plus those of tagging pdp are driving some updated resource mapping use cases.

**Comment by jakedoublev** [comment]
Is it accurate that obligations are applied to entities, and not resources? If the environment is an Entity, and we want to apply obligations based on an environment, I think that association should live within Subject Mappings and not Resource Mappings?

**Comment by ttschampel** [comment]
In my mind Resource Mappings would be used to create the mapping policy between data attributes->obligation attributes and Subject Mappings would be used to entitle SUBJECT or ENVIRONMENT entities

resource mapping example document has attr1/value/foo and attr1/value/bar then a policy mapping exists to infer derived obligations of drm/value/watermark

**Comment by jakedoublev** [comment]
That makes sense. I was considering only the first mapping to indicate a presence of an obligation, and not entitlement to it, which is the back half of the need.

**Comment by ttschampel** [comment]
Adding an update here based on [Entity Types ADR](https://github.com/opentdf/platform/issues/1181);  The enum containing the entity types could / should be used to scope obligation to entity by type.  

Conversations around obligations have been predominately around obligations enforced on ENVIRONMENT type entities, but a few use cases for SUBJECT type entities has been provided.

**Comment by ttschampel** [comment]
Capturing some updates from recent conversations
1. Derived Obligations shall be data attribute -> 0..N [obligation attribute + scoped by Entity Category 
(SUBJECT/ENVIRONMENT)]
  * This means Entities are not taken into account as part of derived obligations
1. A new property on Attribute Definition shall be used to identify obligation attributes
1. All obligations will be returned as part of the response.  The PEP is responsible for filtering and understanding these.
