### ISSUE TITLE
bug: Hierarchy decisions defaults to lowest hierarchy level when entity has multiple hierarchy entitlements

### ISSUE THREAD

**Issue by elizabethhealy** [opentdf/platform#880]
When an entity has multiple hierarchy entitlements, ex: Jack, Queen, King, the access pdp seems to default to the lowest attribute and makes a decision based on that.

Should it instead default to the highest level entitlement?

**Comment by pflynn-virtru** [comment]
- When data is tagged, the highest hierarchy level is used.
- When entitling an entity chain (one or many entities), the lowest hierarchy level is used.

**Comment by elizabethhealy** [comment]
> * When data is tagged, the highest hierarchy level is used.
> * When entitling an entity chain (one or many entities), the lowest hierarchy level is used.

@pflynn-virtru that makes sense across multiple entities but what about within one entities entitlements?

**Comment by pflynn-virtru** [comment]
so a single entity has multiple subject mappings that are matched,  (ex. Jack=role/soldier, Queen=role/ruler), then their should be "roll-up" to highest.
The roll-up would be the last stage of a single entity entitlement phase, and before the entity chain process.

**Comment by elizabethhealy** [comment]
actually it looks like choosing the lowest access level was by design even back in v1 access-pdp https://github.com/virtru/access-pdp/blob/5f932c3f1184ff34ee30217214b8b7a59be45db2/pdp/access-pdp.go#L489
should this be a mini adr instead?

**Comment by elizabethhealy** [comment]
closing: defaulting to lowest access level is the intended functionality
