### ISSUE TITLE
support additional elliptic curves

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#881]
We need to support additional elliptic curves in kas and the sdk.  Specifically P384 but should be designed in a way to support  others as well.

https://pkg.go.dev/crypto/elliptic#Curve

**Comment by pflynn-virtru** [comment]
>  No Elliptic Curves less than 256-bits are supported

https://github.com/opentdf/spec/tree/main/schema/nanotdf#31-assumptions

**Comment by pflynn-virtru** [comment]
Is only one key active at a time? meaning `P-384` is the only active key that is served from `kas_public_key` endpoint?
Or are all curves active, and the SDK client can use any for its use case?
