### ISSUE TITLE
Audit Events: Rewrap and Policy CRUD

### ISSUE THREAD

**Issue by pbacon-blaber** [opentdf/platform#884]
Parent: #719 

Get audit events firing for rewrap requests and policy CRUD.

Living document for the audit events and their structure: 
https://whimsical.com/audit-HkQXHSMxu8xaWZUznhFCPW

### Rewrap

Rewrap requests are mostly done and already being emitted. The data being passed in just needs to be tweaked to match the schema defined in the whimsical document above

```json
{
  "object": {
    "type": "key_object",
    "id": "uuid", // policy uuid 
    "name": "string - optional", // not needed
    "attributes": {
      "assertions": [], // new field
      "attrs": [], // data attributes from policy body
      "permissions": [] // - keep empty
    }
  },
  "action": {
    "type": "rewrap",
    "result": "success | failure"
  },
  "owner": {
    "id": "ad484b11-c3ee-44d1-b552-7ee9bdcf33b0",
    "orgId": "ad484b11-c3ee-44d1-b552-7ee9bdcf33b0"
  },
  "actor": {
    "id": "string", // sub claim in token
    "attributes": null
  },
  "eventMetaData": {
    "keyID": "string",
    "policyBinding": "string",
    "tdfFormat": "nanotd ,ztdf, ictdf",
    "algorithm": "..."
  },
  "clientInfo": {
    "userAgent": "string",
    "platform": "string - secure reader, bp, etc..",
    "requestIp": "string",
  },
  "diff": "show's what changed in the object - only needed for update actions",
  "requestId": "uuid", // New Field
  "timestamp": "date"
}
```

### Policy CRUD

This hasn't been implemented yet so will need to be started and will be the bulk of the work for this issue. The format found in the whimsical is here:

```json
{
  "object": {
    "type": "string - [subject_mapping, resource_mapping, attribute_definition, attribute_value, namespace, condition_set, kas_registry,kas_attribute_assignment, ]",
    "id": "uuid",
    "name": "string - optional",
    "attributes": {
      "attrs": [],
      "permissions": [] // - only for user_objects
    }
  },
  "action": {
    "type": "string - [create,  update, delete ]",
    "result": "string - [success, error]"
  },
  "owner": {
    "id": "ad484b11-c3ee-44d1-b552-7ee9bdcf33b0",
    "orgId": "ad484b11-c3ee-44d1-b552-7ee9bdcf33b0"
  },
  "actor": {
    "id": "string", // sub out of access token
    "attributes": {
      "permissions": [],
      "attrs": []
    }
  },
  "eventMetaData": {
    // <meta data>
  },
  "clientInfo": {
    "userAgent": "string",
    "platform": "string - secure reader, bp, etc..",
    "requestIp": "string",
  },
  "diff": "show's what changed in the object - only needed for update actions", // Only on update policy objects
  "timestamp": "date"
}
```

**Comment by pbacon-blaber** [comment]
## A note about `diff`

The `diff` from the audit spec (https://virtru.atlassian.net/l/cp/iJ5L4GpS) doesn't have much information on it, simply stating:

```
"diff": "show's what changed in the object - only needed for update actions", // Only on update policy objects
```

### The Problem

Looking at this further and speaking with @dreyes29 we've confirmed that the format of the audit diff is done with the [microdiff](https://www.npmjs.com/package/microdiff) npm package and looks more like this:

```json
[
    {
        "type": "CREATE",
        "path": [
            "forwardLog",
            1
        ],
        "value": {
            "sender": "user@virtrucanary.com",
            "recipient": "tdf3-user@virtrucanary.com",
            "timestamp": "2024-06-04T18:06:19.795Z"
        }
    },
    {
        "path": [
            "lastModified"
        ],
        "type": "CHANGE",
        "value": "2024-06-04T18:06:19.795Z",
        "oldValue": "2024-06-04T18:06:19.590Z"
    },
    {
        "type": "CREATE",
        "path": [
            "simplePolicy",
            "emailUsers",
            1
        ],
        "value": "tdf3-user@virtrucanary.com"
    }
]
```

This is very close to the [JSON patch](https://datatracker.ietf.org/doc/html/rfc6902) defined in RFC 6902. There are a couple of Go packages that support this spec:

- https://github.com/wI2L/jsondiff
- https://github.com/evanphx/json-patch

### Possible Solutions

I see two straightforward solutions to this issue:

1. Update the Audit API to support `diff` coming in as a JSON patch in addition to our custom format.
  a. I believe that there is no "validation" of the incoming `diff` to the audit API. So the only real concern here would be that we may have implemented some frontend UI work (in Control Center) to display the diffs there. If that's the case then the changes would be in Control Center instead of Audit API.
2. Just convert the output from one of the JSON Patch libraries above to our "almost JSON patch" format. This shouldn't be very hard as the structure is 90% the same and would just require some variable renames.

**Comment by timburchvirtru** [comment]
@pbacon-blaber we're going to develop a new Audit UI (using the new design system) possibly as soon as next sprint. So I think you can safely ignore that consideration, i.e., how this change might affect frontend clients, and we can code the new UI so that it's compatible with the JSON patch spec.
