### ISSUE TITLE
SDK should not use gRPC interface methods deprecated in v1.64.0

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#893]
https://github.com/opentdf/platform/actions/runs/9308669097/job/25622536334?pr=892#step:8:26

![Screenshot 2024-05-30 at 1 28 37 PM](https://github.com/opentdf/platform/assets/83739412/9b9b6b7a-f8b8-4f45-ba87-d20e624b4f2f)

Calls with `grpc.Dial`, `grpc.DialContext`, and `grpc.WithBlock` should be replaced with their equivalents:
https://github.com/grpc/grpc-go/blob/v1.64.0/clientconn.go#L198
https://github.com/grpc/grpc-go/blob/v1.64.0/clientconn.go#L215

**Comment by jakedoublev** [comment]
Platform still calls `grpc.Dial` directly so this is still an issue.

**Comment by strantalis** [comment]
resolved by https://github.com/opentdf/platform/issues/1584
