### ISSUE TITLE
Key Access Grants and "Multi-KAS" support

### ISSUE THREAD

**Issue by biscoe916** [opentdf/platform#916]
We should support ZTDF with data encryption keys being split or shared across multiple key access objects, each encrypted with a separate key access server's information. To reduce complexity for application developers, we will use 'key access grants' to build KAO schemes for splitting and sharing the key data. These will be based on the attributes assigned to the data item policy. This will allow owners of the attribute schema and data tagging system to plan how key data will be encrypted in the system, possibly splitting the data across multiple domains in a cryptographically secure way, and/or sharing the data to allow access from multiple authorities.

1. Owners/administrators can generate key access grant items in the platform; these will map from data attributes to associated KAS services.
2. Clients (applications) can encrypt a data element, allowing the tagging service and key access grant to assign the KAS encapsulation information via a KAO policy.
3. Any required changes to decrypt are also made
4. Validations must include that shared keys open with a subset of KASes available and authorized, and that splits are honored and if a KAS containing a split denies access or is unavailable decrypt fails.

**Comment by cassandrabailey293** [comment]
initial work is complete: https://github.com/opentdf/platform/pull/1038 follow on ci and testing tickets are being worked. closing.
