### ISSUE TITLE
ADR: Remove Attribute Value Members from Policy and instead house Value groupings in configuration of PDPs

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#984]
### Background

Members were a legacy artifact of the OpenTDF Platform v1 (this is v2) and were kind of a virtualization of attribute values. Some of the following were revealed with the refactor of policy:

1. Value members seemed to only apply to `anyOf` rule attributes, where values were groupings of other values

     - `https://demo.com/attr/association/value/group_c` which has as members the values `group_a` and `group_b`
     - `hierarchy` and `allOf` rules don't really make sense for this grouping

2. It was additional burden placed on platform admins to understand entitlement policy around members, with some significant questions

	- are members always `anyOf` within themselves?
	- how is entitlement resolved if an admin has Subject Mappings pointing directly to a value with members? Is this behavior that should be explicitly prevented? 
	- how is entitlement resolved if an attribute value with members adds members of another attribute definition?

3. Tagging PDP and other PDPs can separately hold configured groupings of values as it makes sense contextually to roll up values appropriately outside of policy decisioning logic

Therefore, the decision was reached to `Remove Attribute Value Members from Policy and instead house Value groupings in configuration of PDPs`

The benefits are:

1. simplified administrative burden when there is only one way to entitle (subject mappings)
2. reduction of policy complexity
3. PDP-specific configuration flexibility without solving every PDP's contextual needs with a one-size-fits-all solution
4. greater unity across definition types (since members only seemed to have use cases within `anyOf` rule attribute definitions)

**Comment by ttschampel** [comment]
By 2 cents:

- Members are currently used by Tagging PDP for computing rollup data policy
- I also think decision logic should be using these member values as part of the decision.  If a data policy with data attribute "someattr" is requested and its attribute definition includes members ["someotherattr"] and requesting entity has "someotherattr" as an entitlement then access should be granted.
- The use of subject mappings to directly entitling attribute values that have members should really not be used except for special cases (if ever?)

**Comment by jakedoublev** [comment]
Does the above align with the architecture direction of the platform as you both see it @jrschumacher @ttschampel ?
